name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Pylint action
        # You may pin to the exact commit or the version.
        # uses: gabriel-milan/action-pylint@5a2e0c4a6af3a7fac3c45e724b96d45f2a7a4352
        uses: gabriel-milan/action-pylint@v1
        with:
          # GitHub token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Path of files
          path: ./
          # If true, the action will fail if pylint finds errors (default is true)
          fail: true
          # If true, the action will send a PR message if pylint finds errors (default is true)
          pr-message: true
      
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        
      - name: Start container
        run: docker-compose -f ./Docker/docker-compose.yml up --build -d

      - name: Install browser dependencies
        run: docker exec Netulla playwright install-deps

      - name: Install playwright browsers
        run: docker exec Netulla playwright install

      - name: Run tests
        run: docker exec Netulla python -m pytest
